package com.job.portal.beans;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobapplications generated by hbm2java
 */
@Entity
@Table(name="jobapplications"
    ,catalog="job_portal"
)
public class Jobapplications  implements java.io.Serializable {


     private Long jobAppId;
     private Jobmaster jobmaster;
     private Userdetails userdetails;
     private Date appliedOn;

    public Jobapplications() {
    }

	
    public Jobapplications(Jobmaster jobmaster, Userdetails userdetails) {
        this.jobmaster = jobmaster;
        this.userdetails = userdetails;
    }
    public Jobapplications(Jobmaster jobmaster, Userdetails userdetails, Date appliedOn) {
       this.jobmaster = jobmaster;
       this.userdetails = userdetails;
       this.appliedOn = appliedOn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jobAppId", unique=true, nullable=false)
    public Long getJobAppId() {
        return this.jobAppId;
    }
    
    public void setJobAppId(Long jobAppId) {
        this.jobAppId = jobAppId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jobId", nullable=false)
    public Jobmaster getJobmaster() {
        return this.jobmaster;
    }
    
    public void setJobmaster(Jobmaster jobmaster) {
        this.jobmaster = jobmaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userId", nullable=false)
    public Userdetails getUserdetails() {
        return this.userdetails;
    }
    
    public void setUserdetails(Userdetails userdetails) {
        this.userdetails = userdetails;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="appliedOn", length=19)
    public Date getAppliedOn() {
        return this.appliedOn;
    }
    
    public void setAppliedOn(Date appliedOn) {
        this.appliedOn = appliedOn;
    }




}


