package com.job.portal.beans;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Qualifications generated by hbm2java
 */
public class Qualifications implements java.io.Serializable {

    private Integer qid;
    private UserDetails userdetails;
    private String qualification;
    private Date lastUsed;
    private String skillLevel;

    public Qualifications() {
    }

    public Qualifications(UserDetails userdetails, String qualification, Date lastUsed, String skillLevel) {
        this.userdetails = userdetails;
        this.qualification = qualification;
        this.lastUsed = lastUsed;
        this.skillLevel = skillLevel;
    }

    public Integer getQid() {
        return this.qid;
    }

    public void setQid(Integer qid) {
        this.qid = qid;
    }

    public UserDetails getUserdetails() {
        return this.userdetails;
    }

    public void setUserdetails(UserDetails userdetails) {
        this.userdetails = userdetails;
    }

    public String getQualification() {
        return this.qualification;
    }

    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    public Date getLastUsed() {
        return this.lastUsed;
    }

    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }

    public String getSkillLevel() {
        return this.skillLevel;
    }

    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }

}
