package com.job.portal.beans_my;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompanyMasterBean generated by hbm2java
 */
@Entity
@Table(name = "CompanyMaster"
)
public class CompanyMasterBean implements java.io.Serializable {

    private long companyID;
    private String about;
    private String address;
    private String companyName;
    private String contactPersonName;
    private String contactPersonNumber;
    private String email;
    private String industry;
    private String phone;
    private String registrationType;
    private boolean shareContactPersonNumber;
    private boolean shareEmail;
    private boolean sharePhone;
    private String size;
    private UserDetailsBean userId;
    private String website;

    public CompanyMasterBean() {
    }

    public CompanyMasterBean(boolean shareContactPersonNumber, boolean shareEmail, boolean sharePhone) {
        this.shareContactPersonNumber = shareContactPersonNumber;
        this.shareEmail = shareEmail;
        this.sharePhone = sharePhone;
    }

    public CompanyMasterBean(String about, String address, String companyName, String contactPersonName, String contactPersonNumber, String email, String industry, String phone, String registrationType, boolean shareContactPersonNumber, boolean shareEmail, boolean sharePhone, String size, UserDetailsBean userId, String website) {
        this.about = about;
        this.address = address;
        this.companyName = companyName;
        this.contactPersonName = contactPersonName;
        this.contactPersonNumber = contactPersonNumber;
        this.email = email;
        this.industry = industry;
        this.phone = phone;
        this.registrationType = registrationType;
        this.shareContactPersonNumber = shareContactPersonNumber;
        this.shareEmail = shareEmail;
        this.sharePhone = sharePhone;
        this.size = size;
        this.userId = userId;
        this.website = website;
    }

    @Id
    @GeneratedValue
    @Column(name = "companyID", nullable = false)
    public long getCompanyID() {
        return this.companyID;
    }

    public void setCompanyID(long companyID) {
        this.companyID = companyID;
    }

    @Column(name = "about")
    public String getAbout() {
        return this.about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    @Column(name = "address")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "companyName")
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Column(name = "contactPersonName")
    public String getContactPersonName() {
        return this.contactPersonName;
    }

    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }

    @Column(name = "contactPersonNumber")
    public String getContactPersonNumber() {
        return this.contactPersonNumber;
    }

    public void setContactPersonNumber(String contactPersonNumber) {
        this.contactPersonNumber = contactPersonNumber;
    }

    @Column(name = "email")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "industry")
    public String getIndustry() {
        return this.industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    @Column(name = "phone")
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "registrationType")
    public String getRegistrationType() {
        return this.registrationType;
    }

    public void setRegistrationType(String registrationType) {
        this.registrationType = registrationType;
    }

    @Column(name = "shareContactPersonNumber", nullable = false)
    public boolean isShareContactPersonNumber() {
        return this.shareContactPersonNumber;
    }

    public void setShareContactPersonNumber(boolean shareContactPersonNumber) {
        this.shareContactPersonNumber = shareContactPersonNumber;
    }

    @Column(name = "shareEmail", nullable = false)
    public boolean isShareEmail() {
        return this.shareEmail;
    }

    public void setShareEmail(boolean shareEmail) {
        this.shareEmail = shareEmail;
    }

    @Column(name = "sharePhone", nullable = false)
    public boolean isSharePhone() {
        return this.sharePhone;
    }

    public void setSharePhone(boolean sharePhone) {
        this.sharePhone = sharePhone;
    }

    @Column(name = "size")
    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    @Column(name = "userId")
    public UserDetailsBean getUserId() {
        return this.userId;
    }

    public void setUserId(UserDetailsBean userId) {
        this.userId = userId;
    }

    @Column(name = "website")
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

}
