package com.job.portal.beans_my;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplicationsBeans generated by hbm2java
 */
@Entity
@Table(name = "JobApplications"
)
public class JobApplicationsBean implements java.io.Serializable {

    private long jobAppId;
    private Date appliedOn;
    private long jobId;
    private long userId;

    public JobApplicationsBean() {
    }

    public JobApplicationsBean(long jobId, long userId) {
        this.jobId = jobId;
        this.userId = userId;
    }

    public JobApplicationsBean(Date appliedOn, long jobId, long userId) {
        this.appliedOn = appliedOn;
        this.jobId = jobId;
        this.userId = userId;
    }

    @Id
    @GeneratedValue

    @Column(name = "jobAppId", nullable = false)
    public long getJobAppId() {
        return this.jobAppId;
    }

    public void setJobAppId(long jobAppId) {
        this.jobAppId = jobAppId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "appliedOn")
    public Date getAppliedOn() {
        return this.appliedOn;
    }

    public void setAppliedOn(Date appliedOn) {
        this.appliedOn = appliedOn;
    }

    @Column(name = "jobId", nullable = false)
    public long getJobId() {
        return this.jobId;
    }

    public void setJobId(long jobId) {
        this.jobId = jobId;
    }

    @Column(name = "userId", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

}
