package com.job.portal.beans_my;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobMasterBean generated by hbm2java
 */
@Entity
@Table(name = "JobMaster"
)
public class JobMasterBean implements java.io.Serializable {

    private long jobId;
    private CompanyMasterBean companyId;
    private Date datePosted;
    private String description;
    private String experience;
    private String functionalArea;
    private String keywords;
    private String location;
    private String qualificationRequired;
    private String salary;
    private String title;
    private String vacancies;

    public JobMasterBean() {
    }

    public JobMasterBean(CompanyMasterBean companyId, Date datePosted, String description, String experience, String functionalArea, String keywords, String location, String qualificationRequired, String salary, String title, String vacancies) {
        this.companyId = companyId;
        this.datePosted = datePosted;
        this.description = description;
        this.experience = experience;
        this.functionalArea = functionalArea;
        this.keywords = keywords;
        this.location = location;
        this.qualificationRequired = qualificationRequired;
        this.salary = salary;
        this.title = title;
        this.vacancies = vacancies;
    }

    @Id
    @GeneratedValue

    @Column(name = "jobId", nullable = false)
    public long getJobId() {
        return this.jobId;
    }

    public void setJobId(long jobId) {
        this.jobId = jobId;
    }

    @Column(name = "companyId")
    public CompanyMasterBean getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(CompanyMasterBean companyId
    ) {
        this.companyId = companyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "datePosted")
    public Date getDatePosted() {
        return this.datePosted;
    }

    public void setDatePosted(Date datePosted) {
        this.datePosted = datePosted;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "experience")
    public String getExperience() {
        return this.experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    @Column(name = "functionalArea")
    public String getFunctionalArea() {
        return this.functionalArea;
    }

    public void setFunctionalArea(String functionalArea) {
        this.functionalArea = functionalArea;
    }

    @Column(name = "keywords")
    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    @Column(name = "location")
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "qualificationRequired")
    public String getQualificationRequired() {
        return this.qualificationRequired;
    }

    public void setQualificationRequired(String qualificationRequired) {
        this.qualificationRequired = qualificationRequired;
    }

    @Column(name = "salary")
    public String getSalary() {
        return this.salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    @Column(name = "title")
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "vacancies")
    public String getVacancies() {
        return this.vacancies;
    }

    public void setVacancies(String vacancies) {
        this.vacancies = vacancies;
    }

}
