package com.job.portal.beans_my;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import com.job.portal.enums.SkillLevel;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QualificationsBeans generated by hbm2java
 */
@Entity
@Table(name = "Qualifications"
)
public class QualificationsBean implements java.io.Serializable {

    private long qId;
    private Date lastUsed;
    private String qualification;
    private SkillLevel skillLevel;
    private UserDetailsBean userId;

    public QualificationsBean() {
    }

    public QualificationsBean(Date lastUsed, String qualification, SkillLevel skillLevel, UserDetailsBean userId) {
        this.lastUsed = lastUsed;
        this.qualification = qualification;
        this.skillLevel = skillLevel;
        this.userId = userId;
    }

    @Id
    @GeneratedValue

    @Column(name = "qId", nullable = false)
    public long getqId() {
        return this.qId;
    }

    public void setqId(long qId) {
        this.qId = qId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "lastUsed")
    public Date getLastUsed() {
        return this.lastUsed;
    }

    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }

    @Column(name = "qualification")
    public String getQualification() {
        return this.qualification;
    }

    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    @Column(name = "skillLevel")
    public SkillLevel getSkillLevel() {
        return this.skillLevel;
    }

    public void setSkillLevel(SkillLevel skillLevel) {
        this.skillLevel = skillLevel;
    }

    @Column(name = "userId")
    public UserDetailsBean getUserId() {
        return this.userId;
    }

    public void setUserId(UserDetailsBean userId) {
        this.userId = userId;
    }

}
