package com.job.portal.beans_my;
// Generated 3 Nov, 2015 12:02:38 AM by Hibernate Tools 4.3.1

import com.job.portal.enums.Gender;
import com.job.portal.enums.UserRoles;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetailsBeans generated by hbm2java
 */
@Entity
@Table(name = "UserDetails"
)
public class UserDetailsBean implements java.io.Serializable {

    private long userId;
    private Date dob;
    private String email;
    private Gender gender;
    private Date joined;
    private String name;
    private String phone;
    private String pwdHash;
    private UserRoles role;
    private String salt;

    public UserDetailsBean() {
    }

    public UserDetailsBean(Date dob, String email, Gender gender, Date joined, String name, String phone, String pwdHash, UserRoles role, String salt) {
        this.dob = dob;
        this.email = email;
        this.gender = gender;
        this.joined = joined;
        this.name = name;
        this.phone = phone;
        this.pwdHash = pwdHash;
        this.role = role;
        this.salt = salt;
    }

    @Id
    @GeneratedValue

    @Column(name = "userId", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dob")
    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Column(name = "email")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "gender")
    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "joined")
    public Date getJoined() {
        return this.joined;
    }

    public void setJoined(Date joined) {
        this.joined = joined;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "phone", length = 10)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "pwdHash")
    public String getPwdHash() {
        return this.pwdHash;
    }

    public void setPwdHash(String pwdHash) {
        this.pwdHash = pwdHash;
    }

    @Column(name = "role")
    public UserRoles getRole() {
        return this.role;
    }

    public void setRole(UserRoles role) {
        this.role = role;
    }

    @Column(name = "salt")
    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

}
